### PR TITLE
fix: aws s3 config add endpoint url

### PR DESCRIPTION
**Pull request by fan-tastic-z**
aws s3 config add endpoint url

### CODE REVIEW

**Comment by kaplanelad** [comment]
Why do you need to override the endpoint_url?

**Comment by fan-tastic-z** [comment]
> Why do you need to override the endpoint_url?

@kaplanelad Did I use it wrong? Where should this endpoint_url be placed?

**Comment by kaplanelad** [comment]
From how I see it, you want to override the URL endpoint in two use cases
1. when you have a proxy
2. for testing I am already doing it [here](https://github.com/kaplanelad/active-storage/blob/main/tests/drivers/aws_s3.rs#L31)

You can see an example [here](https://github.com/awslabs/aws-sdk-rust/tree/main/examples/examples/s3/src/bin); I do not see any usage of endpoint override. 

Most users will not pass this URL (from what I see). We need to make the initializer clean without many fields.
In case the user is advanced and wants to override the endpoint, he can initialize the client and pass it like this [example](https://github.com/kaplanelad/active-storage/blob/main/src/drivers/aws_s3.rs#L83)

**Comment by fan-tastic-z** [comment]
> From how I see it, you want to override the URL endpoint in two use cases
> 
> 1. when you have a proxy
> 2. for testing I am already doing it [here](https://github.com/kaplanelad/active-storage/blob/main/tests/drivers/aws_s3.rs#L31)
> 
> You can see an example [here](https://github.com/awslabs/aws-sdk-rust/tree/main/examples/examples/s3/src/bin); I do not see any usage of endpoint override.
> 
> Most users will not pass this URL (from what I see). We need to make the initializer clean without many fields. In case the user is advanced and wants to override the endpoint, he can initialize the client and pass it like this [example](https://github.com/kaplanelad/active-storage/blob/main/src/drivers/aws_s3.rs#L83)

Ok, thanks, I close this pr

**Pull request closed without merging**
